-- Have-A-Trip · 景点大全 数据库 schema
--
-- 目标库: PostgreSQL 14 及以上
-- 幂等性: 本文件可重复执行(BEGIN/COMMIT 包住, 全部 IF NOT EXISTS / OR REPLACE)
-- 约定:
--   * 时间统一 TIMESTAMPTZ, 由数据库给默认值, 应用不传
--   * 文本统一 TEXT, 不用 VARCHAR(n) —— 长度限制在内容整理阶段只会带来迁移
--   * 主键用 IDENTITY(BIGINT/INTEGER), 不用 SERIAL
--   * 经纬度只用于「同城聚合」等静态计算, 本项目不做地图与定位
--
-- 执行:
--   createdb attraction_atlas
--   psql -d attraction_atlas -v ON_ERROR_STOP=1 -f db/schema.sql

BEGIN;

-- ---------------------------------------------------------------- 迁移记录

CREATE TABLE IF NOT EXISTS schema_version (
    version    TEXT PRIMARY KEY,
    note       TEXT,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- 分类与标签

CREATE TABLE IF NOT EXISTS category (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       TEXT NOT NULL UNIQUE,
    name       TEXT NOT NULL,
    parent_id  INTEGER REFERENCES category(id) ON DELETE SET NULL,
    sort       INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tag (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

-- ---------------------------------------------------------------- 景点档案

CREATE TABLE IF NOT EXISTS attraction (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            TEXT NOT NULL UNIQUE,
    name            TEXT NOT NULL,
    name_en         TEXT,
    summary         TEXT,
    description     TEXT,
    category_id     INTEGER NOT NULL REFERENCES category(id) ON DELETE RESTRICT,
    country_code    TEXT NOT NULL DEFAULT 'CN',
    province        TEXT,
    city            TEXT,
    address         TEXT,
    lat             DOUBLE PRECISION CHECK (lat IS NULL OR (lat BETWEEN -90 AND 90)),
    lon             DOUBLE PRECISION CHECK (lon IS NULL OR (lon BETWEEN -180 AND 180)),
    best_season     TEXT,
    suggested_hours NUMERIC(4,1) CHECK (suggested_hours IS NULL OR suggested_hours >= 0),
    ticket_price    NUMERIC(10,2) CHECK (ticket_price IS NULL OR ticket_price >= 0),
    rating_avg      NUMERIC(3,2) NOT NULL DEFAULT 0
                    CHECK (rating_avg >= 0 AND rating_avg <= 5),
    rating_count    INTEGER NOT NULL DEFAULT 0 CHECK (rating_count >= 0),
    cover_image     TEXT,
    status          TEXT NOT NULL DEFAULT 'draft'
                    CHECK (status IN ('draft', 'published', 'archived')),
    -- 数据来源与许可是必填: S5 的许可声明页由它聚合生成, 也是「将来可闭源」的数据层保险
    source          TEXT NOT NULL,
    license         TEXT NOT NULL,
    source_url      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_attraction_status   ON attraction (status);
CREATE INDEX IF NOT EXISTS idx_attraction_category ON attraction (category_id);
CREATE INDEX IF NOT EXISTS idx_attraction_city     ON attraction (city);
CREATE INDEX IF NOT EXISTS idx_attraction_rating   ON attraction (rating_avg DESC, rating_count DESC);
-- 关键字搜索走 lower(name) 前缀匹配。装得上 pg_trgm 时可以再补 GIN 索引做模糊搜索:
--   CREATE EXTENSION IF NOT EXISTS pg_trgm;
--   CREATE INDEX ... USING gin (name gin_trgm_ops);
-- pg_trgm 需要较高权限, 所以不在这里默认创建。
CREATE INDEX IF NOT EXISTS idx_attraction_name_lower ON attraction (lower(name));

CREATE TABLE IF NOT EXISTS attraction_tag (
    attraction_id INTEGER NOT NULL REFERENCES attraction(id) ON DELETE CASCADE,
    tag_id        INTEGER NOT NULL REFERENCES tag(id) ON DELETE CASCADE,
    PRIMARY KEY (attraction_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_attraction_tag_tag ON attraction_tag (tag_id);

CREATE TABLE IF NOT EXISTS attraction_image (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attraction_id INTEGER NOT NULL REFERENCES attraction(id) ON DELETE CASCADE,
    url           TEXT NOT NULL,
    caption       TEXT,
    -- 署名与许可是必填: 图片比文字更容易踩许可问题
    credit        TEXT NOT NULL,
    license       TEXT NOT NULL,
    sort          INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (attraction_id, url)
);

CREATE INDEX IF NOT EXISTS idx_attraction_image_owner ON attraction_image (attraction_id, sort);

-- ------------------------------------------------------------- 用户与行为日志

CREATE TABLE IF NOT EXISTS app_user (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 匿名设备标识。不做账号体系, 也不采集定位
    device_id    TEXT NOT NULL UNIQUE,
    nickname     TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS behavior_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    attraction_id INTEGER NOT NULL REFERENCES attraction(id) ON DELETE CASCADE,
    event_type    TEXT NOT NULL
                  CHECK (event_type IN ('view', 'favorite', 'rate', 'share')),
    rating        NUMERIC(3,2) CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5)),
    dwell_ms      INTEGER CHECK (dwell_ms IS NULL OR dwell_ms >= 0),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- 口径: 只有 rate 事件才应该带 rating
    CONSTRAINT behavior_rate_needs_rating CHECK (event_type <> 'rate' OR rating IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_behavior_user_time ON behavior_log (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_behavior_item      ON behavior_log (attraction_id, event_type);

-- ---------------------------------------------------------------- 推荐结果表

-- API 只读这张表, 绝不 import recbole(依赖冲突, 见 docs/BASES.md)。
-- 内容相似度冷启动是 API 实时算的, 不落这张表。
CREATE TABLE IF NOT EXISTS rec_result (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    attraction_id INTEGER NOT NULL REFERENCES attraction(id) ON DELETE CASCADE,
    score         DOUBLE PRECISION,
    -- 从 1 开始。API 按 rank 升序返回, 不按 score —— 不同算法的分数不可比
    rank          INTEGER NOT NULL CHECK (rank >= 1),
    algo          TEXT NOT NULL,
    reason        TEXT NOT NULL,
    -- 一次训练产出一个 batch_id; 回写按 batch 原子切换, 训练失败不影响线上
    batch_id      TEXT NOT NULL,
    generated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, attraction_id, batch_id)
);

CREATE INDEX IF NOT EXISTS idx_rec_user_rank ON rec_result (user_id, rank);
CREATE INDEX IF NOT EXISTS idx_rec_batch     ON rec_result (batch_id);

-- 每个用户取最近一次生成的结果。API 直接读这个视图, 免去自己算 max(generated_at)
CREATE OR REPLACE VIEW v_latest_rec AS
SELECT r.id,
       r.user_id,
       r.attraction_id,
       r.score,
       r.rank,
       r.algo,
       r.reason,
       r.batch_id,
       r.generated_at
FROM rec_result r
JOIN (
    SELECT user_id, max(generated_at) AS generated_at
    FROM rec_result
    GROUP BY user_id
) latest
  ON latest.user_id = r.user_id
 AND latest.generated_at = r.generated_at;

-- ---------------------------------------------------------------- 触发器

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_attraction_updated_at ON attraction;
CREATE TRIGGER trg_attraction_updated_at
    BEFORE UPDATE ON attraction
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------- 版本登记

INSERT INTO schema_version (version, note)
VALUES ('0001_init', '景点档案 / 分类标签 / 行为日志 / 推荐结果')
ON CONFLICT (version) DO NOTHING;

COMMIT;