-- Have-A-Trip · 景点大全 数据库 schema
--
-- 目标库: PostgreSQL 14 及以上
-- 幂等性: 本文件可重复执行(BEGIN/COMMIT 包住, 全部 IF NOT EXISTS / OR REPLACE)
-- 约定:
--   * 时间统一 TIMESTAMPTZ, 由数据库给默认值, 应用不传
--   * 文本统一 TEXT, 不用 VARCHAR(n) —— 长度限制在内容整理阶段只会带来迁移
--   * 主键用 IDENTITY(BIGINT/INTEGER), 不用 SERIAL
--   * 经纬度只用于「同城聚合」等静态计算, 本项目不做地图与定位
--
-- 执行:
--   createdb attraction_atlas
--   psql -d attraction_atlas -v ON_ERROR_STOP=1 -f db/schema.sql

BEGIN;

-- ---------------------------------------------------------------- 迁移记录

CREATE TABLE IF NOT EXISTS schema_version (
    version    TEXT PRIMARY KEY,
    note       TEXT,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- 分类与标签

CREATE TABLE IF NOT EXISTS category (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       TEXT NOT NULL UNIQUE,
    name       TEXT NOT NULL,
    parent_id  INTEGER REFERENCES category(id) ON DELETE SET NULL,
    sort       INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tag (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

-- ---------------------------------------------------------------- 景点档案

CREATE TABLE IF NOT EXISTS attraction (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            TEXT NOT NULL UNIQUE,
    name            TEXT NOT NULL,
    name_en         TEXT,
    summary         TEXT,
    description     TEXT,
    category_id     INTEGER NOT NULL REFERENCES category(id) ON DELETE RESTRICT,
    country_code    TEXT NOT NULL DEFAULT 'CN',
    province        TEXT,
    city            TEXT,
    address         TEXT,
    -- 景区质量等级(GB/T 17775《旅游景区质量等级的划分与评定》)。该标准只适用于
    -- 中国大陆景区, 境外景点一律留空。**留空的意思是「未核实」, 不是「没有等级」** ——
    -- 名录会调整, 只填能核实的, 宁可空着。
    a_level         TEXT CONSTRAINT attraction_a_level_check
                    CHECK (a_level IS NULL OR a_level IN ('5A', '4A', '3A')),
    -- 世界遗产类别, 只对列入 UNESCO《世界遗产名录》的景点有值。
    -- 境外景点的「等级」看这个字段, 因为 A 级标准不跨国。
    heritage        TEXT CONSTRAINT attraction_heritage_check
                    CHECK (heritage IS NULL OR heritage IN ('cultural', 'natural', 'mixed')),
    lat             DOUBLE PRECISION CHECK (lat IS NULL OR (lat BETWEEN -90 AND 90)),
    lon             DOUBLE PRECISION CHECK (lon IS NULL OR (lon BETWEEN -180 AND 180)),
    best_season     TEXT,
    suggested_hours NUMERIC(4,1) CHECK (suggested_hours IS NULL OR suggested_hours >= 0),
    ticket_price    NUMERIC(10,2) CHECK (ticket_price IS NULL OR ticket_price >= 0),
    rating_avg      NUMERIC(3,2) NOT NULL DEFAULT 0
                    CHECK (rating_avg >= 0 AND rating_avg <= 5),
    rating_count    INTEGER NOT NULL DEFAULT 0 CHECK (rating_count >= 0),
    cover_image     TEXT,
    status          TEXT NOT NULL DEFAULT 'draft'
                    CHECK (status IN ('draft', 'published', 'archived')),
    -- 数据来源与许可是必填: S5 的许可声明页由它聚合生成, 也是「将来可闭源」的数据层保险
    source          TEXT NOT NULL,
    license         TEXT NOT NULL,
    source_url      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 升级既有库: `CREATE TABLE IF NOT EXISTS` 不会给已存在的表补列, 所以这里补一遍。
-- 全是 IF NOT EXISTS / 先查 pg_constraint, 新库和老库都能重复执行。
ALTER TABLE attraction ADD COLUMN IF NOT EXISTS a_level  TEXT;
ALTER TABLE attraction ADD COLUMN IF NOT EXISTS heritage TEXT;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'attraction_a_level_check') THEN
        ALTER TABLE attraction ADD CONSTRAINT attraction_a_level_check
            CHECK (a_level IS NULL OR a_level IN ('5A', '4A', '3A'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'attraction_heritage_check') THEN
        ALTER TABLE attraction ADD CONSTRAINT attraction_heritage_check
            CHECK (heritage IS NULL OR heritage IN ('cultural', 'natural', 'mixed'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_attraction_a_level  ON attraction (a_level)  WHERE a_level IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_attraction_heritage ON attraction (heritage) WHERE heritage IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_attraction_status   ON attraction (status);
CREATE INDEX IF NOT EXISTS idx_attraction_category ON attraction (category_id);
CREATE INDEX IF NOT EXISTS idx_attraction_city     ON attraction (city);
CREATE INDEX IF NOT EXISTS idx_attraction_rating   ON attraction (rating_avg DESC, rating_count DESC);
-- 关键字搜索走 lower(name) 前缀匹配。装得上 pg_trgm 时可以再补 GIN 索引做模糊搜索:
--   CREATE EXTENSION IF NOT EXISTS pg_trgm;
--   CREATE INDEX ... USING gin (name gin_trgm_ops);
-- pg_trgm 需要较高权限, 所以不在这里默认创建。
CREATE INDEX IF NOT EXISTS idx_attraction_name_lower ON attraction (lower(name));

CREATE TABLE IF NOT EXISTS attraction_tag (
    attraction_id INTEGER NOT NULL REFERENCES attraction(id) ON DELETE CASCADE,
    tag_id        INTEGER NOT NULL REFERENCES tag(id) ON DELETE CASCADE,
    PRIMARY KEY (attraction_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_attraction_tag_tag ON attraction_tag (tag_id);

CREATE TABLE IF NOT EXISTS attraction_image (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attraction_id INTEGER NOT NULL REFERENCES attraction(id) ON DELETE CASCADE,
    url           TEXT NOT NULL,
    caption       TEXT,
    -- 署名与许可是必填: 图片比文字更容易踩许可问题
    credit        TEXT NOT NULL,
    license       TEXT NOT NULL,
    sort          INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (attraction_id, url)
);

CREATE INDEX IF NOT EXISTS idx_attraction_image_owner ON attraction_image (attraction_id, sort);

-- ---------------------------------------------------------------- 旅游方案
--
-- 「怎么玩」是独立于「是什么」的内容: 一个景点可以有多个方案(半日 / 一日 / 亲子),
-- 方案由有序的步骤组成, 步骤按天分组。
--
-- 方案与景点一样要写清 source 与 license —— 它是本仓库自采的内容, 不是从别处搬的。

CREATE TABLE IF NOT EXISTS attraction_plan (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attraction_id INTEGER NOT NULL REFERENCES attraction(id) ON DELETE CASCADE,
    slug          TEXT NOT NULL UNIQUE,
    title         TEXT NOT NULL,
    -- 行程天数。半日游也计 1 天, 半日用下面的 duration_hours 表达
    days          INTEGER NOT NULL DEFAULT 1 CONSTRAINT plan_days_check
                  CHECK (days >= 1 AND days <= 30),
    -- 花费档次。只给档次不给金额: 具体价格是易变信息, 见 db/README.md 的口径
    budget_level  TEXT CONSTRAINT plan_budget_check
                  CHECK (budget_level IS NULL OR budget_level IN ('free', 'low', 'mid', 'high')),
    best_for      TEXT,
    summary       TEXT NOT NULL,
    source        TEXT NOT NULL,
    license       TEXT NOT NULL,
    source_url    TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_plan_attraction ON attraction_plan (attraction_id);

CREATE TABLE IF NOT EXISTS attraction_plan_step (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id        INTEGER NOT NULL REFERENCES attraction_plan(id) ON DELETE CASCADE,
    day_no         INTEGER NOT NULL DEFAULT 1 CONSTRAINT plan_step_day_check CHECK (day_no >= 1),
    sort           INTEGER NOT NULL DEFAULT 0,
    title          TEXT NOT NULL,
    detail         TEXT NOT NULL,
    duration_hours NUMERIC(4, 1)
                   CONSTRAINT plan_step_hours_check
                   CHECK (duration_hours IS NULL OR duration_hours >= 0),
    tip            TEXT,
    -- 同一天里 sort 不能重复, 否则步骤顺序就没有确定含义了
    CONSTRAINT uq_plan_step_order UNIQUE (plan_id, day_no, sort)
);

CREATE INDEX IF NOT EXISTS idx_plan_step_plan ON attraction_plan_step (plan_id, day_no, sort);

-- ------------------------------------------------------------- 用户与行为日志

CREATE TABLE IF NOT EXISTS app_user (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 匿名设备标识。不做账号体系, 也不采集定位
    device_id    TEXT NOT NULL UNIQUE,
    nickname     TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS behavior_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    attraction_id INTEGER NOT NULL REFERENCES attraction(id) ON DELETE CASCADE,
    event_type    TEXT NOT NULL
                  CHECK (event_type IN ('view', 'favorite', 'rate', 'share')),
    rating        NUMERIC(3,2) CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5)),
    dwell_ms      INTEGER CHECK (dwell_ms IS NULL OR dwell_ms >= 0),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- 口径: 只有 rate 事件才应该带 rating
    CONSTRAINT behavior_rate_needs_rating CHECK (event_type <> 'rate' OR rating IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_behavior_user_time ON behavior_log (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_behavior_item      ON behavior_log (attraction_id, event_type);

-- ---------------------------------------------------------------- 推荐结果表

-- API 只读这张表, 绝不 import recbole(依赖冲突, 见 docs/BASES.md)。
-- 内容相似度冷启动是 API 实时算的, 不落这张表。
CREATE TABLE IF NOT EXISTS rec_result (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    attraction_id INTEGER NOT NULL REFERENCES attraction(id) ON DELETE CASCADE,
    score         DOUBLE PRECISION,
    -- 从 1 开始。API 按 rank 升序返回, 不按 score —— 不同算法的分数不可比
    rank          INTEGER NOT NULL CHECK (rank >= 1),
    algo          TEXT NOT NULL,
    reason        TEXT NOT NULL,
    -- 一次训练产出一个 batch_id; 回写按 batch 原子切换, 训练失败不影响线上
    batch_id      TEXT NOT NULL,
    generated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, attraction_id, batch_id)
);

CREATE INDEX IF NOT EXISTS idx_rec_user_rank ON rec_result (user_id, rank);
CREATE INDEX IF NOT EXISTS idx_rec_batch     ON rec_result (batch_id);

-- 每个用户取最近一次生成的结果。API 直接读这个视图, 免去自己算 max(generated_at)
CREATE OR REPLACE VIEW v_latest_rec AS
SELECT r.id,
       r.user_id,
       r.attraction_id,
       r.score,
       r.rank,
       r.algo,
       r.reason,
       r.batch_id,
       r.generated_at
FROM rec_result r
JOIN (
    SELECT user_id, max(generated_at) AS generated_at
    FROM rec_result
    GROUP BY user_id
) latest
  ON latest.user_id = r.user_id
 AND latest.generated_at = r.generated_at;

-- ---------------------------------------------------------------- 触发器

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_attraction_updated_at ON attraction;
CREATE TRIGGER trg_attraction_updated_at
    BEFORE UPDATE ON attraction
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_attraction_plan_updated_at ON attraction_plan;
CREATE TRIGGER trg_attraction_plan_updated_at
    BEFORE UPDATE ON attraction_plan
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------- 语义检索

-- 一个景点在一个模型下的一条向量。
-- 联合唯一 (attraction_id, model): 切换模型期间新旧向量可以并存, 但同一模型只能有一条。
-- embedding 存 JSON 数组文本而不是 pgvector: 本仓库的模型层刻意只用可移植类型,
-- 让测试能跑 SQLite 内存库(见 backend/app/models.py 开头与 backend/app/search/vectors.py)。
-- 目录过万条时再换 pgvector + HNSW, 接口不用改。
CREATE TABLE IF NOT EXISTS attraction_embedding (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attraction_id    INTEGER NOT NULL REFERENCES attraction(id) ON DELETE CASCADE,
    -- 形如 "ollama:bge-m3:auto", 见 backend/app/llm/embedding.py 的 signature
    model            TEXT NOT NULL,
    dim              INTEGER NOT NULL CONSTRAINT embedding_dim_check CHECK (dim > 0),
    -- 拼串口径版本, 参与指纹。见 backend/app/search/canonical.py
    pipeline_version TEXT NOT NULL,
    -- sha256(model + pipeline_version + 规范化文本), 用于判断要不要重算
    content_hash     TEXT NOT NULL,
    embedding        TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_embedding_item_model UNIQUE (attraction_id, model)
);

CREATE INDEX IF NOT EXISTS idx_embedding_model_item ON attraction_embedding (model, attraction_id);

-- ---------------------------------------------------------------- 行程生成

-- 按 (owner, 天) 的计数器。限额与预算靠它做成原子操作。
-- 为什么不用 count(itinerary): 「先查条数再写入」在并发下不是原子的, 两个请求会同时通过检查。
-- 这里用一条 `UPDATE ... WHERE used < :limit` 拿到行锁并自增, 靠 rowcount 判断有没有抢到名额。
-- owner_key = '__global__' 的那一行是全站 token 预算。
CREATE TABLE IF NOT EXISTS trip_quota (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_key   TEXT NOT NULL,
    -- 日期字符串 YYYY-MM-DD。用文本而不是 DATE: 两种数据库的时区处理不一样,
    -- 这里要的是「哪个自然日」这个纯分组键, 由应用算好再传进来。
    day         TEXT NOT NULL,
    used        INTEGER NOT NULL DEFAULT 0 CHECK (used >= 0),
    tokens_used INTEGER NOT NULL DEFAULT 0 CHECK (tokens_used >= 0),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_quota_owner_day UNIQUE (owner_key, day)
);

CREATE INDEX IF NOT EXISTS idx_quota_day ON trip_quota (day);

-- 一次「自然语言需求 -> 按天行程」的生成任务。
-- 表名叫 itinerary 而不是 trip_plan: 库里已经有一个 attraction_plan(景点自带的静态方案),
-- 两个 plan 并排会让「改哪个」永远要回去查定义。
CREATE TABLE IF NOT EXISTS itinerary (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 对外只用 token。自增 id 可枚举 —— 递增就能读到别人的需求原文, 见 backend/app/api/itineraries.py
    public_token    TEXT NOT NULL UNIQUE,
    -- user_id 有就给 'u:<id>', 否则 'd:<device_id>'。缓存与限额都以它为作用域。
    owner_key       TEXT NOT NULL,
    days            INTEGER NOT NULL
                    CONSTRAINT itinerary_days_check CHECK (days >= 1 AND days <= 14),
    -- 只存 hash, 不存需求原文: 原文里常有同行人、预算这类个人信息
    request_hash    TEXT NOT NULL,
    constraints     TEXT,
    status          TEXT NOT NULL DEFAULT 'pending'
                    CONSTRAINT itinerary_status_check
                    CHECK (status IN ('pending', 'generating', 'succeeded', 'failed', 'rejected')),
    error           TEXT,
    note            TEXT,
    model           TEXT,
    prompt_tokens   INTEGER CONSTRAINT itinerary_prompt_tokens_check
                    CHECK (prompt_tokens IS NULL OR prompt_tokens >= 0),
    completion_tokens INTEGER CONSTRAINT itinerary_completion_tokens_check
                    CHECK (completion_tokens IS NULL OR completion_tokens >= 0),
    -- 单价快照: 服务商调价后, 历史行程的成本仍然按当时的价算
    unit_price      NUMERIC(10, 6),
    cache_key       TEXT NOT NULL,
    -- 回收判据。多 worker 下只看「generating 超时」会误杀别人正在跑的任务, 必须认领 + 心跳
    worker_id       TEXT,
    started_at      TIMESTAMPTZ,
    heartbeat_at    TIMESTAMPTZ,
    generated_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- 并发抢锁点: 同一个 owner 的同一份需求只能有一行
    CONSTRAINT uq_itinerary_owner_cache UNIQUE (owner_key, cache_key)
);

CREATE INDEX IF NOT EXISTS idx_itinerary_owner_time ON itinerary (owner_key, created_at);
CREATE INDEX IF NOT EXISTS idx_itinerary_status_heartbeat ON itinerary (status, heartbeat_at);

-- 行程里的一站。attraction_id 一定落在生成时的候选集内, 由 validator 保证。
CREATE TABLE IF NOT EXISTS itinerary_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itinerary_id    BIGINT NOT NULL REFERENCES itinerary(id) ON DELETE CASCADE,
    -- RESTRICT 而不是 CASCADE: 行程是用户产出, 不因为景点被删就悄悄少一站。
    -- 景点下架走 status='archived' 软删, 硬删要走显式的数据清理流程。
    attraction_id   INTEGER NOT NULL REFERENCES attraction(id) ON DELETE RESTRICT,
    -- 名称快照: 景点改名或下架后, 回看历史行程仍然显示当时的那一刻
    attraction_name TEXT NOT NULL,
    day_index       INTEGER NOT NULL CONSTRAINT item_day_check CHECK (day_index >= 1),
    seq             INTEGER NOT NULL CONSTRAINT item_seq_check CHECK (seq >= 1),
    note            TEXT NOT NULL,
    reason          TEXT NOT NULL,
    CONSTRAINT uq_itinerary_item_order UNIQUE (itinerary_id, day_index, seq)
);

CREATE INDEX IF NOT EXISTS idx_itinerary_item_order ON itinerary_item (itinerary_id, day_index, seq);

-- ---------------------------------------------------------------- 用户动态

-- 全项目唯一由用户产出自由文本的地方。四条口径写在 backend/app/models.py 的 Post 上,
-- 这里只说库这一层: 库只保证「有内容、别超长、状态是两态之一」, 对用户承诺的 500 字
-- 由 schemas.py 管 —— 库的上限(1000)是防漏的底线, 故意比产品上限宽。
CREATE TABLE IF NOT EXISTS post (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    -- 署名快照: 只属于这一条, 改了昵称不会把历史动态一起改掉
    author_name     TEXT NOT NULL DEFAULT '游客',
    body            TEXT NOT NULL,
    -- SET NULL: 景点被硬删不连坐删掉别人写的动态, 只是那一行的链接没了
    attraction_id   INTEGER REFERENCES attraction(id) ON DELETE SET NULL,
    attraction_name TEXT,
    status          TEXT NOT NULL DEFAULT 'visible'
                    CONSTRAINT post_status_check CHECK (status IN ('visible', 'hidden')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT post_body_not_blank    CHECK (length(body) >= 1),
    CONSTRAINT post_body_length_check CHECK (length(body) <= 1000),
    CONSTRAINT post_author_length_check CHECK (length(author_name) <= 40)
);

-- 列表按 id 倒序取(与游标同序, 见 backend/app/api/posts.py); 我的动态按 (user_id, id DESC)。
-- 用 id 而不是 created_at: 游标是整数比较, 在 PostgreSQL 与 SQLite 上结果一致
CREATE INDEX IF NOT EXISTS idx_post_status_id ON post (status, id DESC);
CREATE INDEX IF NOT EXISTS idx_post_user_id   ON post (user_id, id DESC);
-- updated_at 触发器。必须写在两张表建好之后 —— 触发器不能挂在不存在的表上。
-- 复用上面 251 行定义的 set_updated_at()。配额计数器是用 UPDATE 自增的,
-- 没有这个触发器它的 updated_at 永远停在插入那一刻。
DROP TRIGGER IF EXISTS trg_attraction_embedding_updated_at ON attraction_embedding;
CREATE TRIGGER trg_attraction_embedding_updated_at
    BEFORE UPDATE ON attraction_embedding
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_trip_quota_updated_at ON trip_quota;
CREATE TRIGGER trg_trip_quota_updated_at
    BEFORE UPDATE ON trip_quota
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_post_updated_at ON post;
CREATE TRIGGER trg_post_updated_at
    BEFORE UPDATE ON post
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------- 版本登记

INSERT INTO schema_version (version, note)
VALUES ('0001_init', '景点档案 / 分类标签 / 行为日志 / 推荐结果')
ON CONFLICT (version) DO NOTHING;

INSERT INTO schema_version (version, note)
VALUES ('0002_plans', '景点质量等级与世界遗产字段 / 旅游方案与行程步骤')
ON CONFLICT (version) DO NOTHING;

INSERT INTO schema_version (version, note)
VALUES ('0003_ai', '景点语义向量 / LLM 行程生成 / 限额计数')
ON CONFLICT (version) DO NOTHING;

INSERT INTO schema_version (version, note)
VALUES ('0004_posts', '用户动态(自由文本, 可挂景点, 无自动审核)')
ON CONFLICT (version) DO NOTHING;

COMMIT;
