-- Have-A-Trip · 景点配图的种子数据
--
-- 本文件由 scripts/make_attraction_covers.py 生成, **不要手改**。
-- 改图或加景点请改那个脚本再重跑, 否则 CI 的 --check 会拦下来。
--
-- 封面是自绘的 SVG, 出处就是仓库里的脚本本身, 许可与仓库一致(MIT)。
-- 为什么不用第三方照片: 见 docs/LICENSE-AUDIT.md 第五节。
--
-- 幂等: 用 upsert, 重跑会把 caption / credit / license 同步成本文件的版本。
--
-- 执行:
--   psql -d attraction_atlas -v ON_ERROR_STOP=1 -f db/seed/images.sql

BEGIN;

INSERT INTO attraction_image (attraction_id, url, caption, credit, license, sort) VALUES
    ((SELECT id FROM attraction WHERE slug = 'west-lake'), '/images/covers/west-lake.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'huangshan'), '/images/covers/huangshan.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'jiuzhaigou'), '/images/covers/jiuzhaigou.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'zhangjiajie'), '/images/covers/zhangjiajie.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'taishan'), '/images/covers/taishan.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'huashan'), '/images/covers/huashan.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'lijiang-river'), '/images/covers/lijiang-river.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'qinghai-lake'), '/images/covers/qinghai-lake.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'daocheng-yading'), '/images/covers/daocheng-yading.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'changbai-mountain'), '/images/covers/changbai-mountain.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'hulunbuir'), '/images/covers/hulunbuir.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'kanas'), '/images/covers/kanas.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'terracotta-army'), '/images/covers/terracotta-army.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'badaling-great-wall'), '/images/covers/badaling-great-wall.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'mogao-caves'), '/images/covers/mogao-caves.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'yungang-grottoes'), '/images/covers/yungang-grottoes.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'longmen-grottoes'), '/images/covers/longmen-grottoes.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'pingyao'), '/images/covers/pingyao.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'ming-xiaoling'), '/images/covers/ming-xiaoling.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'huaqing-palace'), '/images/covers/huaqing-palace.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'yinxu'), '/images/covers/yinxu.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'liangzhu'), '/images/covers/liangzhu.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'palace-museum'), '/images/covers/palace-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'national-museum'), '/images/covers/national-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'shanghai-museum'), '/images/covers/shanghai-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'shaanxi-history-museum'), '/images/covers/shaanxi-history-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'sanxingdui-museum'), '/images/covers/sanxingdui-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'suzhou-museum'), '/images/covers/suzhou-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'the-bund'), '/images/covers/the-bund.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'oriental-pearl-tower'), '/images/covers/oriental-pearl-tower.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'canton-tower'), '/images/covers/canton-tower.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'temple-of-heaven'), '/images/covers/temple-of-heaven.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'summer-palace'), '/images/covers/summer-palace.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'orange-isle'), '/images/covers/orange-isle.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'lingyin-temple'), '/images/covers/lingyin-temple.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'potala-palace'), '/images/covers/potala-palace.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'mount-emei'), '/images/covers/mount-emei.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'leshan-buddha'), '/images/covers/leshan-buddha.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'wudang-mountain'), '/images/covers/wudang-mountain.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'wuzhen'), '/images/covers/wuzhen.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'zhouzhuang'), '/images/covers/zhouzhuang.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'xitang'), '/images/covers/xitang.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'hongcun'), '/images/covers/hongcun.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'lijiang-old-town'), '/images/covers/lijiang-old-town.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'fenghuang'), '/images/covers/fenghuang.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'shanghai-disney'), '/images/covers/shanghai-disney.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'chimelong-ocean-kingdom'), '/images/covers/chimelong-ocean-kingdom.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'universal-beijing'), '/images/covers/universal-beijing.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'window-of-the-world'), '/images/covers/window-of-the-world.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'hangzhou-songcheng'), '/images/covers/hangzhou-songcheng.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'shanghai-natural-history-museum'), '/images/covers/shanghai-natural-history-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'nanjing-museum'), '/images/covers/nanjing-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'hubei-museum'), '/images/covers/hubei-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'henan-museum'), '/images/covers/henan-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'hunan-museum'), '/images/covers/hunan-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'jinsha-site-museum'), '/images/covers/jinsha-site-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'guangdong-museum'), '/images/covers/guangdong-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'china-science-technology-museum'), '/images/covers/china-science-technology-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'guangzhou-chimelong'), '/images/covers/guangzhou-chimelong.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'happy-valley-beijing'), '/images/covers/happy-valley-beijing.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'shanghai-haichang-park'), '/images/covers/shanghai-haichang-park.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'happy-valley-shenzhen'), '/images/covers/happy-valley-shenzhen.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'happy-valley-wuhan'), '/images/covers/happy-valley-wuhan.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'happy-valley-chengdu'), '/images/covers/happy-valley-chengdu.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'happy-valley-chongqing'), '/images/covers/happy-valley-chongqing.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'hongkong-disneyland'), '/images/covers/hongkong-disneyland.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'shanghai-tower'), '/images/covers/shanghai-tower.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'citic-tower'), '/images/covers/citic-tower.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'ping-an-finance-center'), '/images/covers/ping-an-finance-center.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'hongya-cave'), '/images/covers/hongya-cave.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'yellow-crane-tower'), '/images/covers/yellow-crane-tower.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'tianjin-eye'), '/images/covers/tianjin-eye.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'xian-bell-tower'), '/images/covers/xian-bell-tower.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'macau-tower'), '/images/covers/macau-tower.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'shenyang-imperial-palace'), '/images/covers/shenyang-imperial-palace.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'palace-museum-of-manchukuo'), '/images/covers/palace-museum-of-manchukuo.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'harbin-saint-sophia-cathedral'), '/images/covers/harbin-saint-sophia-cathedral.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'inner-mongolia-museum'), '/images/covers/inner-mongolia-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'shanxi-museum'), '/images/covers/shanxi-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'hebei-museum'), '/images/covers/hebei-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'zhaozhou-bridge'), '/images/covers/zhaozhou-bridge.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'shandong-museum'), '/images/covers/shandong-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'baotu-spring'), '/images/covers/baotu-spring.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'zhanqiao-pier'), '/images/covers/zhanqiao-pier.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'anhui-museum'), '/images/covers/anhui-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'tengwang-pavilion'), '/images/covers/tengwang-pavilion.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'three-lanes-seven-alleys'), '/images/covers/three-lanes-seven-alleys.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'gulangyu-island'), '/images/covers/gulangyu-island.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'stone-forest'), '/images/covers/stone-forest.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'jiaxiu-pavilion'), '/images/covers/jiaxiu-pavilion.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'guangxi-museum-of-nationalities'), '/images/covers/guangxi-museum-of-nationalities.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'gansu-provincial-museum'), '/images/covers/gansu-provincial-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'western-xia-tombs'), '/images/covers/western-xia-tombs.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'kumbum-monastery'), '/images/covers/kumbum-monastery.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'xinjiang-regional-museum'), '/images/covers/xinjiang-regional-museum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'tianyi-pavilion'), '/images/covers/tianyi-pavilion.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'yandang-mountain'), '/images/covers/yandang-mountain.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'yuantouzhu'), '/images/covers/yuantouzhu.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'foshan-ancestral-temple'), '/images/covers/foshan-ancestral-temple.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'quanzhou-kaiyuan-temple'), '/images/covers/quanzhou-kaiyuan-temple.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'angkor-wat'), '/images/covers/angkor-wat.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'taj-mahal'), '/images/covers/taj-mahal.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'mount-fuji'), '/images/covers/mount-fuji.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'petra'), '/images/covers/petra.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'borobudur'), '/images/covers/borobudur.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'hagia-sophia'), '/images/covers/hagia-sophia.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'ha-long-bay'), '/images/covers/ha-long-bay.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'kinkakuji'), '/images/covers/kinkakuji.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'gyeongbokgung'), '/images/covers/gyeongbokgung.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'eiffel-tower'), '/images/covers/eiffel-tower.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'colosseum'), '/images/covers/colosseum.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'sagrada-familia'), '/images/covers/sagrada-familia.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'versailles'), '/images/covers/versailles.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'neuschwanstein'), '/images/covers/neuschwanstein.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'acropolis'), '/images/covers/acropolis.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'santorini'), '/images/covers/santorini.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'stonehenge'), '/images/covers/stonehenge.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'pompeii'), '/images/covers/pompeii.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'louvre'), '/images/covers/louvre.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'jungfrau'), '/images/covers/jungfrau.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'charles-bridge'), '/images/covers/charles-bridge.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'pyramids-of-giza'), '/images/covers/pyramids-of-giza.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'victoria-falls'), '/images/covers/victoria-falls.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'serengeti'), '/images/covers/serengeti.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'marrakech-medina'), '/images/covers/marrakech-medina.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'table-mountain'), '/images/covers/table-mountain.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'grand-canyon'), '/images/covers/grand-canyon.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'statue-of-liberty'), '/images/covers/statue-of-liberty.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'yellowstone'), '/images/covers/yellowstone.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'chichen-itza'), '/images/covers/chichen-itza.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'banff'), '/images/covers/banff.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'niagara-falls'), '/images/covers/niagara-falls.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'machu-picchu'), '/images/covers/machu-picchu.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'christ-the-redeemer'), '/images/covers/christ-the-redeemer.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'iguazu-falls'), '/images/covers/iguazu-falls.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'galapagos'), '/images/covers/galapagos.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'easter-island'), '/images/covers/easter-island.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'sydney-opera-house'), '/images/covers/sydney-opera-house.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'great-barrier-reef'), '/images/covers/great-barrier-reef.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0),
    ((SELECT id FROM attraction WHERE slug = 'milford-sound'), '/images/covers/milford-sound.svg', '自绘示意图', 'Have-A-Trip 自绘', 'MIT', 0)
ON CONFLICT (attraction_id, url) DO UPDATE SET
    caption = EXCLUDED.caption,
    credit  = EXCLUDED.credit,
    license = EXCLUDED.license,
    sort    = EXCLUDED.sort;

-- 列表卡片的封面就是这张 sort = 0 的图。放在这里同步, 免得 attraction.cover_image
-- 和 attraction_image 指向两张不同的图(seed.sql 的 DO UPDATE 不碰 cover_image)。
UPDATE attraction a
SET cover_image = i.url
FROM attraction_image i
WHERE i.attraction_id = a.id
  AND i.sort = 0
  AND a.cover_image IS DISTINCT FROM i.url;

COMMIT;
