# -*- coding: utf-8 -*-
"""从 Wikimedia Commons 抓景点实景照片, 产出 db/seed/photos.json 与封面文件。

为什么要有这个脚本: 仓库里的配图分两种, 自绘的 SVG 由 make_attraction_covers.py
生成, 抓来的实景照片由本脚本产出 —— 都留脚本, 出处才查得到。台账逐张记
pid / seq / slug / photo / license / artist / source, 落库到 attraction_image。

许可口径(与 docs/LICENSE-AUDIT.md 第五节一致):
  只收 Public domain / CC0 / CC BY / CC BY-SA; 排除 NC / ND / 非自由;
  脚本只能保证"没收录错许可", 署名义务靠人看 —— CC BY-SA 有相同方式共享义务,
  CC BY 有署名义务, 用到就得在声明页逐图署名。前端目前只把封面的 credit
  聚合成一行, 逐图署名仍是缺口, 见 docs/LICENSE-AUDIT.md 第五节。

网络: Wikimedia 在中国大陆直连不通(TLS 握手上被重置), 需要能出去的代理, 形如
      --proxy http://127.0.0.1:7890; 代理会轮换重试, 坏掉的自动跳过。
      不确定本机命令行走不走代理(浏览器能上不等于命令行能上), 先跑
      python scripts/system_proxy.py 看一眼: 它会把 WinINET / WinHTTP / 环境变量
      三层分开报出来, 并实测一次请求。

用法:
  python scripts/fetch_commons_photos.py --proxy-file proxies.txt --levels 5A --width 800
  python scripts/fetch_commons_photos.py --redo --slugs-file retry.txt
  python scripts/fetch_commons_photos.py --check     # 只校验台账与磁盘上的封面
  python scripts/fetch_commons_photos.py --proxy-file p.txt --audit   # 复查台账里有没有非实拍

抓完接着跑 python scripts/make_attraction_covers.py 把台账编进 db/seed/images.sql。
--check 退出码: 0 一致, 1 有对不上的条目。
"""
import argparse, concurrent.futures as cf, csv, io, json, re, sys, time
import http.client, socket, ssl
from pathlib import Path
from urllib.parse import urlencode, urlsplit

ROOT = Path(__file__).resolve().parents[1]
PHOTOS_JSON = ROOT / "db" / "seed" / "photos.json"
COVER_DIR = ROOT / "frontend" / "public" / "images" / "covers"
SEED_PATHS = (ROOT / "db" / "seed" / "seed.sql", ROOT / "db" / "seed" / "attractions_cn.sql")
CN_CSV = ROOT / "db" / "seed" / "data" / "cn_a_level.csv"


def read_text(path):
    """按 UTF-8 读文本。utf-8-sig 让带 BOM 的文件也能读(种子里混着 BOM 过)。"""
    return io.open(path, encoding="utf-8-sig").read()
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

UA = "Have-A-Trip-PhotoFetcher/0.1 (Wikimedia Commons; one-off public-data fetch)"
# 作者取不到时的兜底。必须与 make_attraction_covers.PHOTO_CREDIT_FALLBACK 是同一句话:
# Commons 上有文件根本没写作者, 空着不但看着像「我们忘了填」, --check 也会判它不合格
# (2026-09-26 抓到 74 张, 其中 4a-beijing-041 就是这么被 --check 拦下的)。
ARTIST_FALLBACK = "Wikimedia Commons 用户"

ALLOW = ("cc0", "public domain", "cc by", "cc-by", "pd-")
BAD = re.compile(
    r"landsat|satellite|sentinel|modis|map\b|locator|logo|diagram|schematic|floor ?plan|"
    r"\bchart\b|coat of arms|\bflag\b|\bseal\b|stamp|banknote|screenshot|\bicon\b|"
    r"drawing|painting|sketch|\bposter\b|panorama ?360|qr ?code|infographic|"
    r"hospital|airport|railway|metro station|bus station|parking|toll|"
    r"机场|醫院|医院|火车站|地铁站|車站|车站|停车场|收费站|"
    # 同名车站与军舰: 2026-09-26 过目新图时逮到的两类配错 —— 陈家祠配成「陈家祠站台」,
    # 深圳野生动物园配成「动物园站」, 长白山配成军舰 PLANS Changbai Mountain。
    r"列车|高铁|动车|公交|车辆|车站|地铁|轻轨|站台|電車|駅|"
    r"\bstations?\b|platforms?\b|\bPLANS\b|\bLPD-?\d|\bUSS\b|\bHMS\b|\bship\b|\bvessel\b|"
    r"圖卷|图卷|画卷|清趣|絹本|纸本|紙本|图象|圖象|版画|木刻|古籍|拓片|书影|書影|"
    r"engraving|woodcut|lithograph|etching|manuscript|scroll|illustration|"
    r"\.svg$|\.pdf$|\.gif$", re.I)
# 类别与描述里的「这不是照片」信号。文件名会骗人(刚抓到的西湖那张叫《漂海录》西湖图象.jpg,
# 是一张古籍木刻插图, 名字里既没有 painting 也没有 drawing), 类别骗不了人: Commons 的
# AI 生成图、版画、木刻、舆图、手稿各有各的类别, 这里整批挡掉。
CATBAD = re.compile(
    r"ai-generated|ai generated|artificial intelligence|stable diffusion|midjourney|"
    r"dall-?e|computer-generated|generated by|3d render|\bcgi\b|"
    r"woodcut|engraving|etching|lithograph|printmaking|ukiyo|"
    r"paintings?|drawings?|sketches|illustrations?|manuscripts?|scrolls?|calligraphy|"
    r"\bmaps?\b|atlas|diagrams?|coats of arms|satellite images|"
    r"舆图|舆圖|地图|地圖|版画|木刻|古籍|拓片|碑帖|书画|绘画|插图|手绘|线描|白描", re.I)
CITY = re.compile(r"^.{1,8}?(市|自治州|地区|省|县|区|盟|旗)")
SUFFIX = re.compile(
    r"(风景名胜区|风景区|旅游景区|旅游区|景区|国家森林公园|森林公园|自然保护区|"
    r"度假区|旅游度假区|博物馆|纪念馆|古城|古镇|遗址|石窟|陵园|陵|公园|湿地|"
    r"大峡谷|峡谷|瀑布|溶洞|温泉|滑雪场|文化区|文化园|广场)$")
PUNCT = re.compile(r"[•·、，,\-—()（）\s]+")


def strip_html(s):
    return re.sub(r"<[^>]+>", " ", s or "").replace("&amp;", "&").strip()


def norm(s):
    return PUNCT.sub("", s or "").strip()


def levels_of():
    """slug -> "5A" / "4A" / "3A"。

    两处来源, 少一处就会漏掉一批景点: 名录条目的等级写在 db/seed/data/cn_a_level.csv,
    自采档案(黄山、故宫那一批)的等级写在 db/seed/seed.sql 的等级映射表里。
    在库外把等级算出来, 是为了让 --levels 不依赖数据库也能跑。
    """
    out = {}
    if CN_CSV.exists():
        with io.open(CN_CSV, encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                slug = (row.get("slug") or "").strip()
                grade = (row.get("grade") or "").strip().upper()
                if slug and grade:
                    out[slug] = grade
    text = read_text(SEED_PATHS[0])
    for m in re.finditer(r"^\s*\('([a-z0-9-]+)',\s*'(5A|4A|3A|2A|1A)',", text, re.M):
        out.setdefault(m.group(1), m.group(2))
    return out


ADMIN = re.compile(r"(特别行政区|自治区|自治州|地区|市|省|区|县|盟|旗)$")


def cities_of():
    """slug -> (城市核心名, 省份核心名)。名录 CSV 里有省市两列, 去掉「市 / 省 / 区」这类尾字。"""
    out = {}
    if CN_CSV.exists():
        with io.open(CN_CSV, encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                slug = (row.get("slug") or "").strip()
                if slug:
                    out[slug] = (ADMIN.sub("", (row.get("city") or "").strip()),
                                 ADMIN.sub("", (row.get("province") or "").strip()))
    return out


def city_tokens():
    """所有出现过的地名核心词, 用来判「文件里写着的地方跟这个景点不是一处」。"""
    toks = set()
    for city, prov in cities_of().values():
        for x in (city, prov):
            if len(x) >= 2:
                toks.add(x)
    return sorted(toks, key=len, reverse=True)


# 一次算好: 每个候选都要拿它扫一遍, 每次重算太亏。
CITY_TOKENS = None


def wrong_place(text, place, name):
    """文件里写着的地方跟这个景点不是一处 —— 同名车站 / 别的城市就是这么混进来的。

    地名不能是这个景点自己名字的一部分, 否则「北京市中山公园景区」会被「中山市」误伤
    (中山公园 - panoramio.jpg 是张好图)。天津规划展览馆 配给 东莞市展览馆 则是真的配错。
    """
    global CITY_TOKENS
    if CITY_TOKENS is None:
        CITY_TOKENS = city_tokens()
    for tok in CITY_TOKENS:
        if tok in text and tok not in place and tok not in name:
            return tok
    return None


def variants(name):
    """名录里是全称(丽江市玉龙雪山景区), Commons 文件名常用核心名(玉龙雪山)。"""
    base = norm(name)
    out = [base]
    for c in (CITY.sub("", base), SUFFIX.sub("", base),
              SUFFIX.sub("", CITY.sub("", base)), CITY.sub("", SUFFIX.sub("", base))):
        c = norm(c)
        if len(c) >= 2 and c not in out:
            out.append(c)
    return out


def licence_ok(short, terms):
    s, t = (short or "").lower(), (terms or "").lower()
    if re.search(r"[\s-](nc|nd)\b", s) or "noncommercial" in t or "noderiv" in t:
        return False
    if "fair use" in s or "non-free" in s or "copyright" in s:
        return False
    return any(a in s for a in ALLOW) or "public domain" in t or "cc0" in t

def nonphoto_reason(c):
    """这张候选「不是实拍」的理由; 是合格照片就给 None。"""
    if BAD.search(c.get("file") or ""):
        return "文件名的字面"
    blob = " ".join([c.get("file") or "", c.get("desc") or ""] + list(c.get("categories") or []))
    if CATBAD.search(blob):
        return "类别 / 描述"
    return None


class Pool:
    """轮换用代理池; 全部标记坏掉之后清空重来。"""

    def __init__(self, entries):
        self.entries = list(entries)
        self.bad = set()
        self.lock = __import__("threading").Lock()

    def pick(self):
        with self.lock:
            live = [e for e in self.entries if e not in self.bad]
            if not live:
                self.bad.clear()
                live = list(self.entries)
        import random
        return random.choice(live)

    def note(self, entry, ok):
        with self.lock:
            if ok:
                self.bad.discard(entry)
            else:
                self.bad.add(entry)

    def get(self, host, path, timeout=12, tries=None):
        tries = tries or max(6, len(self.entries) * 2)
        last = "?"
        for _ in range(tries):
            entry = self.pick()
            try:
                status, body = self._one(entry, host, path, timeout)
                if status == 200:
                    self.note(entry, True)
                    return body
                last = "HTTP %d" % status
            except Exception as e:
                last = "%s: %s" % (type(e).__name__, e)
            self.note(entry, False)
        raise RuntimeError("代理都不通, 最后错误 %s" % last)

    def _one(self, entry, host, path, timeout):
        kind, ph, pp = entry
        if kind == "http":
            c = http.client.HTTPSConnection(ph, pp, timeout=timeout)
            c.set_tunnel(host, 443)
            c.request("GET", path, headers={"User-Agent": UA, "Accept": "*/*"})
            r = c.getresponse()
            status, body = r.status, r.read()
            c.close()
            return status, body
        s = socket.create_connection((ph, pp), timeout)
        s.settimeout(timeout)
        s.sendall(b"\x05\x01\x00")
        if s.recv(2)[:1] != b"\x05":
            s.close()
            raise OSError("not socks5")
        h = host.encode()
        s.sendall(b"\x05\x01\x00\x03" + bytes([len(h)]) + h + (443).to_bytes(2, "big"))
        rep = s.recv(10)
        if len(rep) < 2 or rep[1] != 0:
            s.close()
            raise OSError("socks5 reject")
        tls = ssl.create_default_context().wrap_socket(s, server_hostname=host)
        tls.sendall(("GET %s HTTP/1.1\r\nHost: %s\r\nUser-Agent: %s\r\n"
                     "Accept: */*\r\nConnection: close\r\n\r\n" % (path, host, UA)).encode())
        chunks = []
        while True:
            b = tls.recv(65536)
            if not b:
                break
            chunks.append(b)
        tls.close()
        head, _, body = b"".join(chunks).partition(b"\r\n\r\n")
        parts = head.split(b" ")
        if len(parts) < 2:
            raise OSError("bad status line")
        return int(parts[1]), body


def api(pool, host, params, tries=4):
    params = dict(params)
    params.setdefault("format", "json")
    params.setdefault("formatversion", 2)
    path = "/w/api.php?" + urlencode(params)
    last = None
    for _ in range(tries):
        try:
            return json.loads(pool.get(host, path))
        except json.JSONDecodeError as e:
            # 拿到 200 也不一定是 JSON: 中间代理会把自家的错误页塞回来。
            # 这种响应不算「Commons 上没有」, 换个代理再来 —— 否则复查会把
            # 一堆好图误报成「查不到」(2026-09-26 复查 131 张, 39 条就是这么来的)。
            last = e
    raise RuntimeError("拿不到 JSON: %s" % last)


def search(pool, query, limit, width):
    j = api(pool, "commons.wikimedia.org", {
        "action": "query", "generator": "search",
        "gsrsearch": "%s filetype:bitmap" % query, "gsrnamespace": 6, "gsrlimit": limit,
        "prop": "imageinfo|categories", "iiprop": "url|size|mime|extmetadata",
        "iiurlwidth": width, "cllimit": "max"})
    out = []
    for p in (j.get("query") or {}).get("pages") or []:
        c = parse_page(p)
        if c:
            out.append(c)
    return out


def file_meta(pool, title):
    """按文件名回查一条(复查台账时用): 类别 / 描述 / 许可都取回来。"""
    j = api(pool, "commons.wikimedia.org", {
        "action": "query", "titles": title, "prop": "imageinfo|categories",
        "iiprop": "url|size|mime|extmetadata", "cllimit": "max"})
    pages = (j.get("query") or {}).get("pages") or []
    return parse_page(pages[0]) if pages else None


def parse_page(p):
    """把一个 page 折成候选字典; 没有 imageinfo 的(比如查不到的文件)给 None。"""
    ii = p.get("imageinfo") or []
    if not ii:
        return None
    ii = ii[0]
    em = ii.get("extmetadata") or {}
    g = lambda k: strip_html((em.get(k) or {}).get("value", ""))
    return {
            "file": p.get("title"), "descriptionurl": ii.get("descriptionurl"),
            "thumb": ii.get("thumburl"), "width": ii.get("width") or 0,
            "height": ii.get("height") or 0, "mime": ii.get("mime") or "",
            "license": g("LicenseShortName"), "terms": g("UsageTerms"),
            "artist": g("Artist")[:120], "desc": g("ImageDescription")[:300],
            "categories": [c.get("title", "") for c in (p.get("categories") or [])],
    }


def score(c, name, name_en, place=None):
    f = c.get("file") or ""
    if nonphoto_reason(c) or not licence_ok(c["license"], c["terms"]):
        return -99
    if c["mime"] not in ("image/jpeg", "image/png") or c["width"] < 1000:
        return -99
    if place and wrong_place(f + " " + (c.get("desc") or ""), place, name):
        return -99
    blob = (f + " " + c.get("desc", "")).lower()
    s = 4 if name and name in (f + " " + c.get("desc", "")) else 0
    toks = [t for t in re.split(r"[^A-Za-z]+", (name_en or "").lower()) if len(t) >= 4]
    hit = [t for t in toks if t in blob]
    s += 3 if len(hit) > 1 else (2 if hit else 0)
    if c["width"] > c["height"]:
        s += 1
    if c["width"] >= 1600:
        s += 1
    return s

def load_attractions(slugs_file=None, levels=None):
    """景点清单取自两个种子文件(与自绘封面同一个来源), 可按 slug 白名单与等级过滤。

    返回 (slug, name, name_en, seq)。seq 是该景点在"先按等级、再按种子文件顺序"里的
    序号 —— 与库里 `order by a_level, id` 的顺序一致(id 就是种子的插入顺序), 台账里的
    seq 就是这么来的: 先定 seq 再抓图, 抓不到的仍然占着号, 所以 seq 有跳号是正常的。
    """
    sys.path.insert(0, str(ROOT / "scripts"))
    import make_attraction_covers as covers
    rows = []
    for p in SEED_PATHS:
        parsed, _skipped = covers.parse_attractions(read_text(p))
        rows.extend(parsed)
    lv = levels_of()
    if levels:
        want_lv = {x.strip().upper() for x in levels if x.strip()}
        rows = [r for r in rows if lv.get(r[0]) in want_lv]
    if slugs_file:
        want = {l.strip() for l in io.open(slugs_file, encoding="utf-8") if l.strip()}
        rows = [r for r in rows if r[0] in want]
    rank = {"5A": 0, "4A": 1, "3A": 2}
    rows.sort(key=lambda r: rank.get(lv.get(r[0]), 3))   # 稳定排序, 同级内保持种子顺序
    return [(slug, name, name_en or "", i)
            for i, (slug, name, name_en, _category) in enumerate(rows, 1)]


def fetch_one(pool, slug, name, name_en, seq, width, min_score, place=None):
    """搜 + 打分 + 下载。搜不到合适照片返回 None(不是异常 —— 冷门景点本来就常没有)。"""
    best, best_s, used = None, 0, None
    for q in variants(name)[:3]:
        try:
            cands = search(pool, q, 8, width)
        except Exception:
            continue
        for c in cands:
            for v in variants(name):
                s = score(c, v, name_en, place)
                if s > best_s:
                    best, best_s, used = c, s, q
        if best_s >= 6:
            break
    if not best or best_s < min_score:
        return None
    url = best["thumb"]
    parts = urlsplit(url)
    if not parts.netloc:
        raise RuntimeError("缩略图地址不完整: %r" % url)
    body = pool.get(parts.netloc, parts.path + ("?" + parts.query if parts.query else ""),
                    timeout=25)
    # 缩略图地址的后缀就是真实格式(可能是 .png / .jpeg), 拿不到才退回 mime 推断。
    suffix = Path(parts.path).suffix.lower()
    ext = suffix if suffix in (".jpg", ".jpeg", ".png") else (
        ".jpg" if "jpeg" in best["mime"] else ".png")
    target = COVER_DIR / (slug + ext)
    target.write_bytes(body)
    # 重抓时格式可能变(上次 .png 这次 .jpg), 不清掉旧文件会留下两张同 slug 的封面。
    for other in (".jpg", ".jpeg", ".png"):
        stale = COVER_DIR / (slug + other)
        if stale != target and stale.exists():
            stale.unlink()
    return {"seq": seq, "slug": slug, "photo": slug + ext, "file": best["file"],
            "license": best["license"], "artist": (best["artist"] or "").strip() or ARTIST_FALLBACK,
            "source": best["descriptionurl"], "width": best["width"],
            "height": best["height"], "from": used}


def check() -> int:
    """只校验台账: 每条都要有许可、作者, 且文件在磁盘上。不联网。"""
    if not PHOTOS_JSON.exists():
        print("没有 %s, 先抓一次" % PHOTOS_JSON.relative_to(ROOT))
        return 1
    items = json.loads(PHOTOS_JSON.read_text(encoding="utf-8"))
    problems = []
    for it in items:
        slug, photo = it.get("slug"), it.get("photo")
        if not slug or not photo:
            problems.append("第 %s 条缺 slug / photo" % it.get("pid"))
            continue
        if not (it.get("license") or "").strip():
            problems.append("%s 缺 license" % slug)
        if not (it.get("artist") or "").strip():
            problems.append("%s 缺 artist" % slug)
        path = COVER_DIR / photo
        if not path.exists() or path.stat().st_size == 0:
            problems.append("%s 台账里写的是 %s, 磁盘上没有" % (slug, photo))
    if problems:
        print("照片台账与磁盘对不上:")
        for p in problems[:40]:
            print("  -", p)
        print("共 %d 条问题" % len(problems))
        return 1
    print("照片台账 %d 条, 与磁盘一致" % len(items))
    return 0


def drop(slugs_file) -> int:
    """把人工过目后判定配错的条目从台账里剔掉, 并删掉对应的封面文件。

    抓图是机器判的, 总有「同名车站 / 军舰 / 别的城市」这种看着像却配错的 —— 2026-09-26
    过目 75 张新图时逮到 9 张。剔掉之后那个景点回到自绘 SVG: 配错比没图更糟。
    """
    want = {l.strip() for l in io.open(slugs_file, encoding="utf-8") if l.strip()}
    items = json.loads(PHOTOS_JSON.read_text(encoding="utf-8"))
    keep, gone = [], []
    for it in items:
        (gone if it["slug"] in want else keep).append(it)
    missing = want - {g["slug"] for g in gone}
    if missing:
        print("台账里没有这些 slug: %s" % ", ".join(sorted(missing)))
    for it in gone:
        p = COVER_DIR / it["photo"]
        if p.exists():
            p.unlink()
    fixed = [{"pid": i, **{k: v for k, v in e.items() if k != "pid"}}
             for i, e in enumerate(keep, 1)]
    io.open(PHOTOS_JSON, "w", encoding="utf-8", newline="\n").write(
        json.dumps(fixed, ensure_ascii=False, indent=2) + "\n")
    print("剔掉 %d 条: %s" % (len(gone), ", ".join(g["slug"] for g in gone[:12])))
    return 0


def repair() -> int:
    """把台账里缺失的字段补齐并写回, 不联网。

    目前只有一种: 作者缺失 —— Commons 上有文件根本没写作者, 抓它那次若还没这条兜底,
    空值就留在账上了(4a-beijing-041)。这条离线可跑, 修老账不必再走一遍网络。
    """
    items = json.loads(PHOTOS_JSON.read_text(encoding="utf-8"))
    filled = []
    for it in items:
        if not (it.get("artist") or "").strip():
            it["artist"] = ARTIST_FALLBACK
            filled.append(it["slug"])
    if not filled:
        print("台账 %d 条, 没有要补的" % len(items))
        return 0
    io.open(PHOTOS_JSON, "w", encoding="utf-8", newline="\n").write(
        json.dumps(items, ensure_ascii=False, indent=2) + "\n")
    print("补上作者的 %d 条: %s" % (len(filled), ", ".join(filled[:10])))
    return 0


def audit(pool) -> int:
    """按当前口径复查台账里的每一张 —— 抓的时候判过一次, 但口径是会长大的。

    老条目里混进过古籍木刻插图(西湖那张《漂海录》)。把复查也做成命令, 「台账里到底有没有
    AI 图 / 画件」才答得出来, 而不是靠印象。退出码 0 干净, 1 有可疑条目。
    """
    items = json.loads(PHOTOS_JSON.read_text(encoding="utf-8"))

    def one(it):
        try:
            c = file_meta(pool, it.get("file") or "")
        except Exception as e:
            return it, "查不到(%s)" % type(e).__name__
        if c is None:
            return it, "Commons 上已经没有这个文件"
        return it, nonphoto_reason(c)

    with cf.ThreadPoolExecutor(max_workers=8) as ex:
        flagged = [(it, r) for it, r in ex.map(one, items) if r]
    print("复查台账 %d 张, 其中不像实拍的 %d 张" % (len(items), len(flagged)))
    for it, reason in flagged:
        print("  %-30s %-12s %s" % (it["slug"], reason, (it.get("file") or "")[:60]))
    return 1 if flagged else 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--proxy", action="append", default=[],
                    help="http://host:port 或 socks5://host:port, 可多次")
    ap.add_argument("--proxy-file", help="每行一个 host:port 的文件, 行首可带 socks5:// 或 http://")
    ap.add_argument("--slugs-file", help="只抓这些 slug(每行一个)")
    ap.add_argument("--levels", default="", help="只抓这些等级, 逗号分隔(如 5A 或 5A,4A); 留空=全部")
    ap.add_argument("--width", type=int, default=800, help="缩略图宽度(px)")
    ap.add_argument("--min-score", type=int, default=4, help="打分低于它就不要这张图")
    ap.add_argument("--threads", type=int, default=8)
    ap.add_argument("--redo", action="store_true", help="连已有照片的景点也重抓")
    ap.add_argument("--check", action="store_true", help="只校验台账与磁盘, 不联网")
    ap.add_argument("--audit", action="store_true", help="按当前口径复查台账(要联网, 要代理)")
    ap.add_argument("--repair", action="store_true", help="补齐台账里缺失的字段(不联网)")
    ap.add_argument("--drop", help="人工过目后要剔掉的 slug 清单(每行一个, 不联网)")
    a = ap.parse_args()
    if a.drop:
        return drop(a.drop)
    if a.repair:
        return repair()
    if a.check:
        return check()

    if not a.proxy and not a.proxy_file:
        print("需要代理: Wikimedia 在中国大陆直连不通。--proxy 或 --proxy-file 给一个。")
        return 2
    entries = []
    for spec in a.proxy:
        kind, _, hp = spec.partition("://")
        if hp:
            host, _, port = hp.rpartition(":")
            entries.append(("socks5" if "socks" in kind else "http", host, int(port)))
        else:
            host, _, port = spec.rpartition(":")
            entries.append(("http", host, int(port)))
    if a.proxy_file:
        for line in io.open(a.proxy_file, encoding="utf-8"):
            line = line.strip()
            if line and ":" in line and not line.startswith("#"):
                # 行可以带 scheme(形如 socks5://host:port), 不带就当 http。
                # 扫出来的存活列表里 socks5 占多数, 一律按 http 试会白轮一圈。
                scheme, sep, rest = line.partition("://")
                if not sep:
                    scheme, rest = "http", scheme
                host, _, port = rest.rpartition(":")
                entries.append(("socks5" if "socks" in scheme.lower() else "http",
                                host, int(port)))
    pool = Pool(entries)
    if a.audit:
        return audit(pool)

    existing = json.loads(PHOTOS_JSON.read_text(encoding="utf-8")) if PHOTOS_JSON.exists() else []
    have = {e["slug"] for e in existing}
    rows = load_attractions(a.slugs_file, [x for x in a.levels.split(",") if x.strip()])
    todo = [r for r in rows if a.redo or r[0] not in have]
    print("景点 %d 个, 已有照片 %d 个, 本次待抓 %d 个" % (len(rows), len(have), len(todo)), flush=True)
    COVER_DIR.mkdir(parents=True, exist_ok=True)

    places = cities_of()   # slug -> (城市核心名, 省份核心名), 判「别的城市」要用
    got, t0 = [], time.time()
    with cf.ThreadPoolExecutor(max_workers=a.threads) as ex:
        futs = {ex.submit(fetch_one, pool, s, n, en, seq, a.width, a.min_score,
                          places.get(s)): s
                for s, n, en, seq in todo}
        for f in cf.as_completed(futs):
            slug = futs[f]
            try:
                r = f.result()
            except Exception as e:
                r = None
                print("  %-30s 失败 %s" % (slug, type(e).__name__), flush=True)
            if r:
                got.append(r)
                print("  %-30s ok  %-16s %s" % (slug, r["license"][:15], r["file"][:44]), flush=True)

    merged = {e["slug"]: e for e in existing}
    for r in got:
        merged[r["slug"]] = r
    ordered = sorted(merged.values(), key=lambda e: (e.get("seq") is None, e.get("seq") or 0))
    fixed = []
    for i, e in enumerate(ordered, 1):
        e.pop("bytes", None)
        e.pop("pid", None)
        # 作者缺失的顺手补齐: 老条目里可能留着空值(抓它那次还没这条兜底),
        # 只在新抓的条目上补, 老账就永远修不好。
        if not (e.get("artist") or "").strip():
            e["artist"] = ARTIST_FALLBACK
        fixed.append({"pid": i, **e})
    # newline="\n" 是必须的: .gitattributes 要求 *.json 用 LF, 而 Path.write_text 在
    # Windows 上会把 \n 翻成 CRLF —— 那样每跑完一次都在工作区留下一份换行不同的文件。
    io.open(PHOTOS_JSON, "w", encoding="utf-8", newline="\n").write(
        json.dumps(fixed, ensure_ascii=False, indent=2) + "\n")
    print("---")
    print("本次抓到 %d 张, 台账共 %d 张, 耗时 %.0fs" % (len(got), len(fixed), time.time() - t0))
    print("台账已写入 %s" % PHOTOS_JSON.relative_to(ROOT))
    print("接着跑: python scripts/make_attraction_covers.py   # 重新生成 images.sql")
    return 0


if __name__ == "__main__":
    sys.exit(main())